title: My blog name
author: Victor Retamaln 
email: victorrtml22@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I write about artificial intelligence, books, maths and science in general. Opinions mny own.

# social links
twitter_username: Victor_Retamal_ # DO NOT include the @ character, or else the build will fail!
github_username:  RetamalVictor # DO NOT include the @ character, or else the build will fail!

#theme
remote_theme: wowthemesnet/affiliates-jekyll-theme

show_excerpts: true # set to false to remove excerpts on the homepage
